CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2
SRC = $(wildcard src/*.cpp)
OBJ = $(SRC:.cpp=.o)
TARGET = disk_simulator

TESTS = tests/test_disk_scheduler.cpp tests/test_file_system.cpp

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

test: $(TESTS)
	$(CXX) $(CXXFLAGS) -I./src -o test_disk $(TESTS[0])
	$(CXX) $(CXXFLAGS) -I./src -o test_fs $(TESTS[1])
	./test_disk
	./test_fs

clean:
	rm -f $(OBJ) $(TARGET) test_disk test_fs

